FinancialControl/Controllers/AccountTypeController.cs
using Dapper;
using FinancialControl.Models;
using FinancialControl.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;

namespace FinancialControl.Controllers
{
    public class AccountTypeController: Controller
    {
        private readonly IAccountTypeRepository accountTypeRepository;
        private readonly IUsersService usersService;

        public AccountTypeController(IAccountTypeRepository accountTypeRepository,
            IUsersService usersService)
        {
            this.accountTypeRepository = accountTypeRepository;
            this.usersService = usersService;
        }

        public IActionResult Create()
        {
            return View();
        }

        public async Task<IActionResult> Index()
        {
            var UserId = 1;
            var accountTypes = await accountTypeRepository.Get(UserId);
            return View(accountTypes);
        }

        [HttpPost]
        public async Task<IActionResult> Create(AccountType accountType)
        {
            if(!ModelState.IsValid)
            {
                return View(accountType);
            }
            accountType.UserId = usersService.GetUserId();

            var AccountTypeExists = await accountTypeRepository.Exists(accountType.Name, accountType.UserId);
            if(AccountTypeExists)
            {
                ModelState.AddModelError(nameof(accountType.Name),
                    $"The name {accountType.Name} already exists");
                return View(accountType);
            }

            await accountTypeRepository.Create(accountType);
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Edit(int Id)
        {
            var UserId = usersService.GetUserId();
            var accountType = await accountTypeRepository.getById(Id, UserId);

            if(accountType == null)
            {
                return RedirectToAction("NotFound", "Home");
            }
            return View(accountType);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(AccountType accountType)
        {
            var UserId = usersService.GetUserId();
            var AccountTypeExists = await accountTypeRepository.getById(accountType.Id, UserId);
            
            if(AccountTypeExists == null)
            {
                return RedirectToAction("NotFound", "Home");
            }
            await accountTypeRepository.Update(accountType);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int Id)
        {
            var UserId = usersService.GetUserId();
            var accountType = await accountTypeRepository.getById(Id, UserId);

            if(accountType == null)
            {
                return RedirectToAction("NotFound", "Home");
            }
            return View(accountType);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteAccountType(int Id)
        {
            var UserId = usersService.GetUserId();
            var accountType = await accountTypeRepository.getById(Id, UserId);

            if (accountType == null)
            {
                return RedirectToAction("NotFound", "Home");
            }
            await accountTypeRepository.Delete(Id);
            return RedirectToAction("Index");
        }


        [HttpGet]
        public async Task<IActionResult> VerifyExistAccountType(string name)
        {
            var UserId = usersService.GetUserId(); 
            var AccountTypeAlreadyExists = await accountTypeRepository.Exists(name, UserId);
            if(AccountTypeAlreadyExists)
            {
                return Json($"The name {name} already exists");
            }
            return Json(true);
        }

        [HttpPost]
        public async Task<IActionResult> Order([FromBody] int[] ids)
        {
            var UserId = usersService.GetUserId();
            var accountTypes = await accountTypeRepository.Get(UserId);
            var accountTypesIds = accountTypes.Select(x => x.Id);

            var accountTypesIdsNotBelongsToUser = ids.Except(accountTypesIds).ToList();

            if(accountTypesIdsNotBelongsToUser.Count > 0)
            {
                return Forbid();
            }

            var accountTypesSorted = ids.Select((value, index) => 
                new AccountType() { Id = value, Orden = index + 1 }).AsEnumerable();
            
            await accountTypeRepository.Order(accountTypesSorted);
            return Ok();
        }
    }
}

FinancialControl/Controllers/CategoryController.cs
using FinancialControl.Models;
using FinancialControl.Services;
using Microsoft.AspNetCore.Mvc;

namespace FinancialControl.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository categoryRepository;
        private readonly IUsersService usersService;

        public CategoryController(ICategoryRepository categoryRepository, IUsersService usersService)
        {
            this.categoryRepository = categoryRepository;
            this.usersService = usersService;
        }

        public IActionResult Create()
        {
            return View();
        }
        
        public async Task<IActionResult> Index()
        {
            var UserId = usersService.GetUserId();
            var categories = await categoryRepository.Get(UserId);
            return View(categories);
        }

        [HttpPost]
        public async Task<IActionResult> Create(Category category)
        {
            if(!ModelState.IsValid)
            {
                return View(category);
            }

            var UserId = usersService.GetUserId();
            category.UserId = UserId;
            await categoryRepository.Create(category);
            return RedirectToAction("Index");

        }

        public async Task<IActionResult> Edit(int Id)
        {
            var UserId = usersService.GetUserId();
            var category = await categoryRepository.GetById(Id, UserId);

            if(category == null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            return View(category);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Category categoryEdit)
        {
            if (!ModelState.IsValid)
            {
                return View(categoryEdit);
            }

            var userId = usersService.GetUserId();
            var category = await categoryRepository.GetById(categoryEdit.Id, userId);

            if(category == null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            categoryEdit.UserId = userId;
            await categoryRepository.Update(categoryEdit);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int Id)
        {
            var UserId = usersService.GetUserId();
            var category = await categoryRepository.GetById(Id, UserId);

            if (category == null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            return View(category);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteCategory(int Id)
        {
            var userId = usersService.GetUserId();
            var category = await categoryRepository.GetById(Id, userId);

            if (category == null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            await categoryRepository.Delete(Id);
            return RedirectToAction("Index");
        }
    }
}

FinancialControl/Controllers/TransactionController.cs
using AutoMapper;
using FinancialControl.Models;
using FinancialControl.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FinancialControl.Controllers
{
    public class TransactionController : Controller
    {
        private readonly IUsersService usersService;
        private readonly IAccountRepository accountRepository;
        private readonly ICategoryRepository categoryRepository;
        private readonly ITransactionsRepository transactionsRepository;
        private readonly IMapper mapper;

        public TransactionController(
            IUsersService usersService, 
            IAccountRepository accountRepository,
            ICategoryRepository categoryRepository,
            ITransactionsRepository transactionsRepository,
            IMapper mapper) {
            this.usersService = usersService;
            this.accountRepository = accountRepository;
            this.categoryRepository = categoryRepository;
            this.transactionsRepository = transactionsRepository;
            this.mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Create()
        {
            var UserId = usersService.GetUserId();
            var model = new TransactionCreateDTO();
            model.Accounts = await GetAccounts(UserId);
            model.Categories = await GetCategories(UserId, model.OperationTypeId);
            return View (model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(TransactionCreateDTO model)
        {
            var UserId = usersService.GetUserId();

            if (!ModelState.IsValid)
            {
                model.Accounts = await GetAccounts(UserId);
                model.Categories = await GetCategories(UserId, model.OperationTypeId);
                return View(model);
            }

            var account = await accountRepository.GetById(model.AccountId, UserId);
            
            if(account is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            var category = await accountRepository.GetById(model.CategoryId, UserId);

            if (category is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            model.UserId = UserId;

            if(model.OperationTypeId == OperationType.Bill)
            {
                model.Amount *= -1;
            }

            await transactionsRepository.Create(model);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int Id)
        {
            var UserId = usersService.GetUserId();
            var transaction = await transactionsRepository.GetById(Id, UserId);

            if(transaction is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            var model = mapper.Map<TransactionUpdateDTO>(transaction);

            model.PrevAmount = model.Amount;

            if(model.OperationTypeId == OperationType.Bill)
            {
                model.PrevAmount = model.Amount * -1;
            }

            model.PrevAccountId = transaction.AccountId;
            model.Categories = await GetCategories(UserId, transaction.OperationTypeId);
            model.Accounts = await GetAccounts(UserId);
            return View(model);
        }

        [HttpPost]

        public async Task<IActionResult> Edit(TransactionUpdateDTO model)
        {
            var UserId = usersService.GetUserId();

            if (!ModelState.IsValid)
            {
                model.Accounts = await GetAccounts(UserId);
                model.Categories = await GetCategories(UserId, model.OperationTypeId);
                return View(model);
            }

            var account = await accountRepository.GetById(model.AccountId, UserId);

            if(account is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            var category = await categoryRepository.GetById(model.CategoryId, UserId);

            if(category is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            var transaction = mapper.Map<Transaction>(model);

            if(model.OperationTypeId == OperationType.Bill)
            {
                transaction.Amount *= -1;
            }

            await transactionsRepository.Update(transaction, model.PrevAmount, model.PrevAccountId);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int Id)
        {
            var UserId = usersService.GetUserId();

            var transaction = await transactionsRepository.GetById(Id, UserId);

            if(transaction is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            await transactionsRepository.Delete(Id);
            return RedirectToAction("Index");
        }

        private async Task<IEnumerable<SelectListItem>> GetAccounts(int UserId)
        {
            var accounts = await accountRepository.Search(UserId);
            return accounts.Select(x => new SelectListItem(x.Name, x.Id.ToString()));
        }

        private async Task<IEnumerable<SelectListItem>> GetCategories(int UserId, OperationType operationType)
        {
            var categories = await categoryRepository.Get(UserId, operationType);
            return categories.Select(x => new SelectListItem(x.Name, x.Id.ToString()));
        }

        [HttpPost]
        public async Task<IActionResult> GetCategories([FromBody] OperationType operationType)
        {
            var UserId = usersService.GetUserId();
            var categories = await GetCategories(UserId, operationType);
            return Ok(categories);
        }
        
    }
}

FinancialControl/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinancialControl</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FinancialControl.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Custom.css" asp-append-version="true" />
    <link rel="stylesheet" href="FinancialControl.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FinancialControl</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AccountType" asp-action="Index">Account Types</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">Accounts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Create">Account Create</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Create">Categories Create</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transaction" asp-action="Index">Transactions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transaction" asp-action="Create">Transaction Create</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FinancialControl - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>